version: '3'

services:
  grid-trading-bot:
    build: .
    container_name: binance-grid-bot
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - BINANCE_TESTNET=False  # Set ke True untuk mode testing
      # Konfigurasi ini memastikan bahwa data grid state dan log tetap ada
      # Tidak perlu menyalin .env karena kita mount seluruh direktori
      # Tambahkan environment variables lain jika diperlukan 